title: AI 与延伸心智
datetime: '2025-10-13T14:06:54+08:00'
tags:
- extended-mind
- cognitive-artifacts
- ai-cognition
description: 探讨 AI 如何成为思维的延伸,从认知人工制品的互补型与竞争型分类,到神经植入带来的内部延伸心智,重新审视人类身份的边界。
source: (Artificiality Institute)[https://www.artificiality.org/ideas/ai-and-the-extended-mind]
attachments:
links:
- (延伸心智理论 - Andy Clark & David Chalmers)[https://en.wikipedia.org/wiki/Extended_mind_thesis]
- (认知人工制品 - David Krakauer)[https://www.santafe.edu/]
