datetime: '2025-10-05T17:46:53.972657+08:00'
source: (源链接)[book_bushman_handbook_files/book.html]
title: 📚 布须曼人（桑人）：为生存而生的智慧

tags:
- anthropology
- survival
- indigenous

attachments:
- (中文PDF)[book.pdf]
- (中文epub)[book.epub]