datetime: '2025-10-29T20:20:39.699190+08:00'
source: (源链接)[https://www.xiaoyuzhoufm.com/episode/68d6ceb2522b40626c7222f0]
title: 商业慢谈 | 对话 Plaud 创始人许高：创业之美与AI新范式
tags:
- ai
- hardware
- entrepreneurship
