title: 资源保存理论（COR）在职场压力与心理健康中的应用
datetime: '2025-12-24T14:49:59+08:00'
tags:
- psychology
- stress
- workplace
description: 介绍资源保存理论（COR）的核心观点、代表性文献、对压力管理的实证启示，以及理论的局限性与学界批评。
source:
attachments:
links:
