title: AI Coding：别被"代码"骗了，这关乎心智的延伸
datetime: '2025-10-13T18:15:51+08:00'
tags:
- ai-coding
- cognition
- mcluhan
description: 从许士伟与马工的工匠与革命之争，到麦克卢汉的延伸理论，再到"一行代码都没写"的启示。探讨 AI Coding 如何重新定义编程，以及我们如何在高科技与高感知之间找到平衡。
source: (原文)[/write/20251013_what_ai_coding2.md]
attachments:
links:
