datetime: '2025-10-12T14:54:39.447060+08:00'
source: (中文课程)[https://appzpimmklbess8.h5.wisapp.cn/pages/course/index?id=5&resellerId=share_77c168044e91a0]
title: Zettelkasten 课程学习笔记
tags:
- zettelkasten
- notes
- obsidian

links:
 - (英文课程)[https://smartnotes.teachable.com/p/how-to-take-smart-notes-in-obsidian]