datetime: '2025-12-24T14:00:44.403880+08:00'
source: (源链接)[https://www.lis.ac.cn/CN/10.13266/j.issn.0252-3116.2025.24.001]
title: 功勋科学家研究：独到发现与核心创新
tags:
- knowledge-management
- scientific-research
- text-mining
