datetime: '2026-02-14T10:55:51.986928+08:00'
source: (源链接)[https://www.bilibili.com/video/BV1kLcWzWEqq/]
title: 深度解析：Vibe Coding 的死结与 Spec 驱动开发的救赎
tags:
- vibe-coding
- spec-driven-development
- agentic-coding
