datetime: '2026-02-17T00:26:50.396693+08:00'
source: (源链接)[https://www.bilibili.com/video/BV1j8ZNBnEGp/]
title: 深度访谈摘要：Guy Podjarny 谈 Spec-Driven Development (Tessl)
tags:
- spec-driven-development
- tessl
- agentic-coding
