datetime: '2026-04-06T19:14:22.798704+08:00'
source: (源链接)[paper_bushcraft_files/book.html]
title: 《丛林技能与原住民知识》全景知识图谱
tags:
- bushcraft
- survival
- outdoor
attachments:
 - (中文DOCX)[book.docx]
links:
 - (英文论文地址)[https://kar.kent.ac.uk/57815/1/207-Bushcraft-and-Indigenous-Knowledge-transformations-of-a-concept-in-the-m.pdf]