title: 媒介与功能：产品战略中的选择
datetime: '2025-12-26T17:52:54+08:00'
tags:
- medium
- product-strategy
- platform
description: 探讨 McLuhan 媒介理论在现代产品设计中的应用，分析什么时候应该做功能、什么时候应该做媒介，以及 AI/LLM 如何成为新的媒介平台。结合产品战略框架与路线图，为构建开放创造生态提供思路。
source: (原文)[write/20251226_medium_vs_features_product_strategy.md]
attachments:
links:
