title: 不要陷入反 AI 的炒作
datetime: '2026-01-12T15:19:49+08:00'
tags:
- ai
- programming
- llm
description: Redis 创始人 antirez 分享了他使用 AI 编程的亲身经历，认为 AI 已经永远改变了编程，建议程序员积极拥抱这一变化，找到让自己能力倍增的方法。
source: (antirez blog)[http://antirez.com/news/153]
attachments:
links:
