datetime: '2025-10-30T19:21:17.157168+08:00'
source: (论文翻译)[paper_trends_in_cognitive_sciences_files/book.html]
title: 论文摘要：复杂技术需要文化创新来分配认知
tags:
 - cognitive
 - culture
 - overload
links:
- (原论文)[https://www.cell.com/trends/cognitive-sciences/fulltext/S1364-6613%2825%2900212-8]