title: 重建数字媒体使用中的平衡
datetime: '2025-10-13T13:49:50+08:00'
tags:
- media
- digital-balance
- slow-movement
description: 探讨如何通过 High Tech / High Touch 平衡原则和慢媒体运动,在数字时代重新找回媒体使用的平衡,避免过度连接和信息过载。
source: (原文)[https://www.onegreenplanet.org/science/escape-the-digital-vortex-and-make-a-difference/]
attachments:
links:
- (理解媒介 - Marshall McLuhan)[https://en.wikipedia.org/wiki/Understanding_Media]
- (慢媒体运动)[https://en.wikipedia.org/wiki/Slow_movement_(culture)]
