title: 抛弃脆弱的精致："百年经典"产品教会我们的设计真谛
datetime: '2025-11-05T11:49:44+08:00'
tags:
- design
- affordance
- pragmatism
description: 通过研究能用百年的经典工具，探讨实用主义设计原则。从19世纪高碳钢刀具到现代消费主义陷阱，揭示可供性（Affordance）概念如何指导产品设计，以及"功能决定形式"的永恒价值。
source:
attachments:
links:
