datetime: '2025-12-15T09:53:04.544146+08:00'
source: (源链接)[report_veracode_genai_code_security_files/book.html]
title: 2025 GenAI 代码安全深度报告
attachments:
 - (英文pdf)[October-2025-GenAI-Code-Security-Report-Update.pdf]
tags:
- code-security
- genai
- research-report
