title: 局外人的故事:澳洲影视创作者 Tony Ayres 的成功之道
datetime: '2025-10-28T20:12:25+08:00'
tags:
- storytelling
- creativity
- identity
description: 澳洲华裔影视创作者 Tony Ayres 的职业访谈,讲述他如何凭借独特的边缘身份视角,在竞争激烈的影视行业中找到自己的声音并取得成功
source: "[Q&A: Filmmaker Tony Ayres on the Secret of His Success](https://colehaddon.substack.com/p/q-and-a-filmmaker-tony-ayres-knows)"
attachments:
links:
