datetime: '2026-01-15T11:23:00.921445+08:00'
source: (源链接)[book_the_effective_executive_files/book.html]
title: 深度解读：《卓有成效的管理者》
tags:
- management
- leadership
- productivity

attachments:
- (中文epub)[book.epub]
