title: AI Coding：心智的延伸，而非思维的终结
datetime: '2025-10-13T18:03:30+08:00'
tags:
- ai-coding
- mcluhan
- philosophy
description: 从麦克卢汉的媒介延伸理论到奈斯比特的高科技高感知平衡，深入探讨 AI Coding 作为人类心智延伸的本质。结合许士伟与马工的实践争论，重新定义 AI 时代编程的核心价值与创造者的终极责任。
source: (原文)[/write/20251013_what_ai_coding.md]
attachments:
links:
