datetime: '2026-02-06T11:53:05.369036+08:00'
source: (源链接)[https://www.bilibili.com/video/BV1dSFzzHEBY/]
title: AI开发新范式：规范驱动开发 (Spec-Driven Development) 深度解析
tags:
- spec-driven-development
- ai-coding
- methodology
