title: 当 AI 写了几乎所有代码，软件工程会怎样？
datetime: '2026-01-14T10:44:46+08:00'
tags:
- ai
- software-engineering
- llm
description: 探讨当 AI 能生成 90% 以上代码时，软件工程职业将如何变化。从资深工程师的顿悟时刻，到 Opus 4.5、GPT-5.2 等模型带来的转折点，分析专业技能价值下降的趋势。
source: (The Pragmatic Engineer)[https://blog.pragmaticengineer.com/]
attachments:
links:
