title: 不变的核心：用 Primitives 做设计
datetime: '2026-01-07T19:59:27+08:00'
tags:
- design
- primitives
- product
description: Ryo Lu 的设计哲学：找到产品的基本构建块（primitives），从核心元素出发设计灵活且连贯的系统，为 AI 时代构建高质量的可复用"砖块"。
source:
attachments:
links:
