datetime: '2026-03-30T13:18:23.110398+08:00'
source: (源链接)[https://letters.thedankoe.com/p/how-to-articulate-yourself-intelligently]
title: 如何聪明地表达自己 - DAN KOE
tags:
- writing
- communication
- self-expression
