title: 用 Vibe Coding 烧坏两台 Mac M4 的 SSD 实录
datetime: '2025-09-29T15:30:24+08:00'
tags:
- ai-coding
- hardware
- ssd
description: 记录了使用AI编程工具导致Mac M4 SSD损坏的真实经历，分析了swap写入过量、程序设计缺陷等根本原因，以及最终的解决方案和反思。
source: (原文)[/write/20250929_vibe_coding_burned_mac_ssd.md]
attachments:
links:
- (B站视频)[https://www.bilibili.com/video/BV1GHnzzPEa7/]