title: 荣格论兴趣变化
datetime: '2025-12-02T10:56:03+08:00'
tags:
- psychology
- jung
- self-growth
description: 荣格心理学视角下的兴趣变化机制：心理能量守恒、自性与人格面具、人生阶段转变，以及如何理解多重兴趣与职业倦怠。
source: (原文)[write/20251201_jung_interest_change_psychology.md]
attachments:
links:
