datetime: '2026-02-17T10:46:47.834158+08:00'
source: (源链接)[https://www.bilibili.com/video/BV1j8ZNBnEpN/]
title: Tessl 发布深度解读 - AI Native Dev
tags:
- spec-driven-development
- agentic-coding
- developer-tools
