datetime: '2026-01-15T23:06:22.206505+08:00'
source: (源链接)[book_jack_straight_from_the_gut_files/book.html]
title: 杰克·韦尔奇商业智慧卡片
tags:
 - jack_welch
 - business_wisdom
attachments:
 - (中文epub)[book.epub]