datetime: '2026-02-08T19:18:37.193781+08:00'
source: (源链接)[book_designing_data_intensive_applications_files/book.html]
title: DDIA 深度精读 - 数据密集型应用系统设计
tags:
- distributed-systems
- architecture
- book
