title: 为什么知识丰富的专家应该保持对做项目的热情
datetime: '2025-12-16T14:31:50+08:00'
tags:
- cognition
- productivity
- rnd
description: 从认知心理学和人类进化角度论证：没有活跃项目，专家的知识讨论会退化为低分辨率闲聊。热情是将知识转化为注意力、证据和改进现实模型的心理引擎。
source:
attachments:
links:
