datetime: '2026-02-25T08:31:26.774551+08:00'
source: (源链接)[https://developers.openai.com/codex/guides/build-ai-native-engineering-team/]
title: 建立 AI 原生工程团队
tags:
- ai-engineering
- coding-agents
- sdlc
