title: 猎人的专注与匠人的手艺：为什么专家在研发中需要目标和热情
datetime: '2025-12-16T17:59:03+08:00'
tags:
- productivity
- psychology
- innovation
description: 探讨专家如何通过清晰目标和热情提升研发效率，结合认知心理学解释选择性注意力机制，以及探索者与匠人角色的平衡之道。
source:
attachments:
links:
