title: AI 时代知识管理与创作的核心矛盾
datetime: '2026-02-05T20:13:17+08:00'
tags:
- ai
- knowledge-management
- cognitive-load
description: 探讨 AI 时代知识管理的核心矛盾：如何在提升效率的同时保持深度思考，通过分离"低维劳动"与"高维思考"实现人机协作的最佳平衡。
source: (原创文章)[/write/20260205_ai_knowledge_management_paradox.md]
attachments:
links:
