title: AI 时代知识管理与创作的核心矛盾
datetime: '2026-02-05T19:38:52+08:00'
tags:
- ai
- knowledge-management
- productivity
description: 探讨 AI 时代知识管理的核心矛盾：技术提升效率的同时如何避免削弱深度思考能力，以及如何通过合理的人机协作实现认知增强而非替代。
source: (原创文章)[/write/20260205_ai_knowledge_management_paradox.md]
attachments:
links:
