title: 为什么资深专家应该保持构建项目的热情
datetime: '2025-12-16T22:38:42+08:00'
tags:
- cognition
- expertise
- learning
description: 从认知心理学和学习科学角度解释为什么资深专家需要保持构建项目的热情。项目提供目标函数、反馈循环和刻意练习结构，防止专业知识僵化，让大脑从图书馆变成猎人。
source:
attachments:
links:
