title: 如何制作弓箭
datetime: '2025-10-13T21:52:31+08:00'
tags:
- survival
- archery
- crafting
description: 从选材到制作,详细介绍如何手工制作传统弓箭的完整流程,包括弓身塑形、弓弦选择、箭杆制作等野外生存技能。
source: (WikiHow - How to Make a Bow and Arrow)[https://www.wikihow.com/Make-a-Bow-and-Arrow]
attachments:
links:
