datetime: '2025-11-03T14:09:19.035307+08:00'
source: (源链接)[https://mp.weixin.qq.com/s/0mscdrcAIN1fH0EempnsmQ]
title: 文章摘要:从"贫嘴张大民的小屋"说起:再论软件开发的系统复杂性
tags:
- complexity
- software-engineering
- software-evolution
links:
 - (代码数字孪生:回归软件的复杂系统属性)[mp_codewisdom_aise_2025_06.html]
 - (智能化时代的软件人才培养)[mp_codewisdom_aise_about_programmer.html]
 - (大模型时代软件智能化开发:我们在哪里?该往何处走?)[mp_codewisdom_aise_way_2024_10.html]
