title: 如何为 LLM 写作才能让它们真正倾听
datetime: '2025-10-28T20:29:42+08:00'
tags:
- llm
- writing
- ai
description: 探讨如何为大语言模型(LLM)创作内容,以确保你的写作能进入AI训练语料库并产生持久影响。涵盖可访问性、主题选择、写作技巧等关键要点。
source: (Writing For LLMs)[https://gwern.net/llm-writing]
attachments:
links:
- (Gwern.net)[https://gwern.net]
