datetime: '2025-12-04T10:58:30.142992+08:00'
source: (源链接)[/ai/blog/20251204_ai_transforming_work_anthropic.html]
title: 深度报告：Anthropic 内部 AI 转型研究 (2025)
tags:
- productivity
- anthropic
- engineering
