title: AI Agent 的有效上下文工程
datetime: '2025-10-27T20:35:11+08:00'
tags:
- context-engineering
- ai-agent
- llm
description: 探讨如何有效策划和管理 AI Agent 的上下文资源，包括上下文工程与提示工程的区别、有效上下文的组成要素、动态检索策略以及长期任务中的压缩、笔记和多 Agent 架构等技术。
source: (Anthropic Blog - Effective context engineering for AI agents)[https://www.anthropic.com/research/context-engineering]
attachments:
links:
- (Claude Developer Platform)[https://www.anthropic.com/claude]
- (Memory and Context Management Cookbook)[https://docs.anthropic.com/en/docs/build-with-claude/cookbook]
