datetime: '2026-02-15T19:27:33.301993+08:00'
source: (源链接)[https://www.bilibili.com/video/BV1p2ZHBCESM/]
title: Confluence 产品负责人深度访谈摘要 - K15T & Jefferson Taylor
tags:
- confluence
- atlassian
- knowledge-management
