datetime: '2025-09-21T09:34:45.287606+08:00'
source: (访谈源链接)[https://www.youtube.com/watch?v=jmHBMtpR36M]
title: 播客摘要：Claude Code 产品负责人 Cat 访谈
tags:
- interview
- PM
- claude
links:
- (访谈中文翻译)[https://www.bilibili.com/video/BV1fkpfzMEjV]