title: 听觉 vs. 视觉信息处理对直觉和分析思维的影响
datetime: '2025-12-23T13:54:31+08:00'
tags:
- cognition
- psychology
- decision-making
description: 探讨听觉与视觉通道如何影响思维方式：听觉信息倾向诱发直觉反应，视觉信息促进分析思考，为信息设计和决策干预提供参考。
source:
attachments:
links:
