datetime: '2026-01-28T11:20:53.558970+08:00'
source: (源链接)[book_deerskins_into_buckskins_files/book.html]
title: 《将鹿皮原皮(Deerskin)按传统工艺鞣制成鹿皮革(Buckskin)》全书深度指南
tags:
- craftsmanship
- traditional-skills
- leather
