title: AI 时代的知识管理：企业与个人的新范式
datetime: '2025-10-11T11:43:39+08:00'
tags:
- knowledge-management
- ai
- data-privacy
description: 探讨 AI 时代企业和个人知识管理的变革，包括源头信息保存、Prompt 库建设、数据隐私保护以及碎片化信息处理的新思路
source:
attachments:
links:
