datetime: '2025-09-24T15:12:44.695023+08:00'
source: (源链接)[【【正片】周鸿祎×罗永浩！近四小时高密度输出！周鸿祎深度谈 AI】 https://www.bilibili.com/video/BV1hNJ1zLEb8/?share_source=copy_web&vd_source=9be84e5d02a1196291c71d9d13d1628f]
title: 周鸿祎 × 罗永浩 访谈摘要（带时间戳）
