datetime: '2026-02-12T19:37:47.540340+08:00'
source: (源链接)[https://www.xiaoyuzhoufm.com/episode/698c9a2d66e2c30377102edf?s=eyJ1IjogIjVlODE3OTE5MWJmYmJjM2RhZDg0OTNhMyJ9]
title: OpenCraw (小龙虾) 深度工程访谈摘要 | 专家版
tags:
- agentic-coding
- open-source
- engineering-culture
