datetime: '2025-12-27T12:53:41.505596+08:00'
source: (源链接)[https://x.com/karpathy/status/2004607146781278521]
title: 'AI & Software Engineering: The Singularity Dialectic'
tags:
- ai
- programming
- software
