title: 人在回路中
datetime: '2026-01-23T17:06:59+08:00'
tags:
- ai
- code-review
- software-engineering
description: 探讨AI时代软件开发的转变：虽然AI可以快速生成代码，但人类的审查、判断和责任依然不可替代。瓶颈已从编码转向审查，判断力成为2026年最重要的技能。
source: (The Human in the Loop)[https://adventures.nodeland.dev/archive/the-human-in-the-loop/]
attachments:
links:
- (原文链接)[https://adventures.nodeland.dev/archive/the-human-in-the-loop/]
