title: 给中风后继续编程的工程师的建议
datetime: '2025-10-29T14:10:24+08:00'
tags:
- health
- productivity
- engineering
description: 一位中风幸存者工程师分享如何在脑损伤后继续编程工作，包括管理疲劳、控制注意力、单线程工作等实用建议。
source: (Tips for stroke-surviving software engineers)[https://blog.j11y.io/2025-10-29_stroke_tips_for_engineers/]
attachments:
links:
