datetime: '2026-01-29T14:57:25.164285+08:00'
source: (源链接)[book_personal_knowledge_polany_files/book.html]
title: 个人知识 (Personal Knowledge) - 完整深度解析
tags:
- epistemology
- philosophy
- tacit-knowledge
