datetime: '2025-09-19T11:50:39.117266+08:00'
source: (Blog中文翻译)[/ai/blog/20250919_ai_not_software.html]
title: '博客摘要: AI 不是软件 (AI Is Not Software)'
tags:
- ai
- software
- development
links:
 - (原blog地址)[https://www.lesswrong.com/posts/iknSNTbb8deJwQuLJ/ai-is-not-software]
