datetime: '2025-10-13T18:24:45.032673+08:00'
source: (源链接)[/ai/blog/20251013_what_ai_coding2.html]
title: AI Coding 摘要：心智的延伸，而非思维的终结
links:
  - (生成博客文章)[/ai/blog/20251013_what_ai_coding.html]
  - (生成博客文章2)[/ai/blog/20251013_what_ai_coding2.html]
