title: AI 编程时代的 Taste：什么是好的代码品味
datetime: '2025-12-26T00:27:02+08:00'
tags:
- taste
- ai-coding
- software-engineering
description: 探讨软件工程中 Taste（品味）的概念，从哲学根源到 AI 辅助编程时代的应用，解析为什么在 AI 时代人类的判断力比生成能力更重要。
source:
attachments:
links:
