datetime: '2025-10-13T21:02:50.171704+08:00'
source: (源链接)[book_monetizing_innovation_files/book.html]
title: 《创新货币化》核心摘要 (含行动卡片)
tags:
 - innovation
 - monetization
 - startup
attachments:
 - (中文epub)[book.epub]