datetime: '2026-02-15T16:05:07.826225+08:00'
source: (源链接)[https://x.com/affaanmustafa/status/2012378465664745795]
title: Claude Code 全方位速查指南 - The Shorthand Guide
tags:
- claude-code
- developer-guide
- cheatsheet
