datetime: '2025-09-19T14:23:12.150868+08:00'
source: (源链接)[https://en.wikipedia.org/wiki/AI_effect]
title: AI效应：核心概念摘要
tags:
- ai
- effect
- concept
links:
 - (larry tesler)[https://www.nomodes.com/larry-tesler-consulting/adages-and-coinages]