datetime: '2025-09-19T15:01:17.397550+08:00'
source: (源链接)[https://techcrunch.com/2025/09/18/atlassian-acquires-dx-a-developer-productivity-platform-for-1b/]
title: 深度解析：Atlassian 收购开发者智能平台 DX
tags:
- acquisition
- developer
- productivity
