title: 社会的技术债务与软件的古腾堡时刻
datetime: '2025-10-29T15:53:07+08:00'
tags:
- ai
- software-engineering
- economics
description: 探讨大语言模型如何通过降低软件生产成本和复杂度，引发软件行业的古腾堡时刻，偿还几十年来的社会技术债务，释放创新浪潮。
source: (Society's Technical Debt and Software's Gutenberg Moment)[https://skventures.substack.com/p/societys-technical-debt-and-softwares]
attachments:
links:
- (Baumol's Cost Disease)[https://en.wikipedia.org/wiki/Baumol%27s_cost_disease]
- (Moore's Law)[https://en.wikipedia.org/wiki/Moore%27s_law]
