title: 记录一切：为什么你应该记录更多的生活
datetime: '2025-12-09T20:40:56+08:00'
tags:
- memory
- lifelog
- philosophy
description: 探讨现代技术如何让记忆增强成为可能，论述为什么我们应该记录更多生活内容。从哲学角度分析记忆对个人身份的重要性，以及生活日志（lifelog）如何帮助我们成为更丰富、更深刻的个体。
source: (原创)[/write/20251209_record_everything.md]
attachments:
links:
