datetime: '2025-10-13T15:45:34.244179+08:00'
source: (源链接)[book_hitech_hitouch_files/book.html]
title: 📚 《高科技 · 高感知》核心摘要
tags:
 - balance
 - high-tech
 - high-touch
attachments:
 - (中文epub)[book.epub]