datetime: '2025-10-05T17:46:01.562129+08:00'
source: (源链接)[book_camplore_and_woodcraft_files/book.html]
title: 📚 《营地传说与野外生存技巧》- 交互式摘要

tags:
- survival
- camping
- outdoors

attachments:
- (中文epub)[book.epub]