datetime: '2025-12-15T11:12:37.060263+08:00'
source: (源链接)[https://www.bilibili.com/video/BV1mcmxBeEjf/]
title: 'Naval Ravikant: The Complete 2025 Insights | 完整报告'
tags:
- philosophy
- wealth
- self-improvement
