datetime: '2026-01-30T17:54:24.330027+08:00'
source: (源链接)[https://www.bilibili.com/video/BV1yP6GBzEGv/]
title: 'Steve Jobs 2026: 重构智能 (Reinventing Intelligence)'
tags:
- ai-philosophy
- product-design
- future
