title: 实战使用概念图和 AI 协作做规划
datetime: '2025-10-31T12:57:37+08:00'
tags:
- ai
- concept-map
- productivity
description: 分享如何用概念图配合 AI 完成项目规划，从手绘草图到可计算的思维图谱，再到协作文档和演示文稿的完整工作流程
source: (原文)[/write/20251031_concept_map_ai_planning.md]
attachments:
links:
