title: 拒绝平庸的平均值：品味是 AI 时代的终极约束
datetime: '2026-01-07T19:33:45+08:00'
tags:
- ai
- taste
- creativity
description: 探讨生成式 AI 时代人类品味的重要性。AI 倾向于产出平均化的"泔水"内容，而人类品味是过滤平庸、引导 AI 走向卓越的终极约束。文章分析了为什么 AI 缺乏品味，以及如何通过迭代和培养判断力来创造真正有价值的作品。
source:
attachments:
links:
