title: 流动界面：AI 如何变革软件 UI 设计
datetime: '2026-01-07T19:46:59+08:00'
tags:
- ai
- ui-design
- ux
description: 探讨用户界面从静态"一刀切"设计向AI驱动的流动界面转变，涵盖自适应UI、生成式界面、设计师角色演变，以及AI作为通用界面层的崛起。
source:
attachments:
links:
