title: Change 的设计哲学
datetime: '2026-02-04T09:59:12+00:00'
tags:
- openspec
- ai-programming
- software-design
description: OpenSpec 的 Change 是人类与 AI 之间的契约层，通过结构化的工作说明书解决 AI 编程中的意图对齐问题。本文深入探讨 Change 的设计哲学、生命周期管理和实践指南。
source: (原文)[/write/20260204_openspec_change.md]
attachments:
links:
