title: 软件工程工作流中的知识抽取与迁移
datetime: '2025-12-15T12:43:06+08:00'
tags:
- knowledge-management
- ai
- rag
description: 探讨如何用 AI 从源代码、commit 历史、会议、聊天中抽取知识，迁移到文档、任务跟踪、架构记录等工作流，打破信息孤岛。
source:
attachments:
links:
