title: AI 参与沟通摘要的关键成功要素（理论注释版）
datetime: '2025-11-19T00:10:55+08:00'
tags:
- ai
- communication
- knowledge-management
description: 从认知心理学和沟通管理学视角，解析 AI 生成高质量会议摘要的五个关键要素，包括完整上下文、高质量讨论、参与者监督、反馈循环和低认知负荷的格式设计。
source:
attachments:
links:
