datetime: '2025-10-11T16:49:41.905825+08:00'
source: (源链接)[https://laobu.com]
title: 创作者的罗盘:开发者心智与AI协作指南
links:
- (大教堂与集市 1999)[book_cathedral_bazaarmusing.html]
- (务实的程序员 1999)[book_pragmatic_programmer.html]
- (敏捷软件开发 2002)[book_agile_development.html]
- (UNIX编程艺术 2003)[book_art_of_unix.html]
- (黑客与画家 2004)[book_hackers_painters.html]
- (持续交付 2010)[book_devops_cd.html]
- (Scrum:敏捷开发的艺术 2014)[book_scrum_halftime_twice_work.html]
tags:
- ai
- development
- mindset
