title: 2025 大语言模型年度回顾
datetime: '2025-12-20T15:48:30+08:00'
tags:
- llm
- ai
- machine-learning
description: 回顾 2025 年大语言模型领域的六大范式转变,包括 RLVR、锯齿状智能、Cursor 应用层、Claude Code、Vibe Coding 和 LLM GUI,探讨这些技术如何重塑 AI 行业格局。
source: (Karpathy 2025 LLM Year in Review)[https://karpathy.bearblog.dev/year-in-review-2025/]
attachments:
links:
