title: AI 如何改变 Anthropic 的工作方式
datetime: '2025-12-04T11:58:18+0800'
tags:
- ai
- productivity
- software-engineering
description: Anthropic 对 132 名工程师和研究人员的调查显示，AI 使用在 60% 的工作中实现 50% 的生产力提升，工程师变得更"全栈"，但也引发了关于技能退化、协作减少和职业不确定性的担忧。
source: (Anthropic 原文)[https://anthropic.com/research/how-ai-is-transforming-work-at-anthropic/]
attachments:
links:
- (AI 流畅性框架)[https://www.anthropic.com/ai-fluency]
- (METR AI 研究)[https://metr.org/]