datetime: '2025-10-10T13:00:58.339227+08:00'
source: (源链接)[book_Psalm_wildbuilt_monk_files/book.html]
title: 📚 书籍摘要：《献给野外建造的赞歌》
tags:
 - nature
 - wildbuilt
 - monk
attachments:
- (中文PDF)[book.pdf]
- (中文epub)[book.epub]