datetime: '2026-02-04T16:54:27.719809+08:00'
source: (源链接)[https://www.bilibili.com/video/BV1aqfRBXEF2/]
title: The Bootstrap 深度访谈：开发者到创始人的蜕变
tags:
- entrepreneurship
- product-development
- marketing
