title: 软件产品设计中的 Function 与 Medium 之辩
datetime: '2025-12-28T21:07:50+08:00'
tags:
- product-design
- platform
- software
description: 探讨软件产品设计中功能型产品与媒介型平台的核心差异，分析两种产品哲学如何影响用户工作流、产品粘性和长期价值，以及AI/LLM作为新媒介的潜力。
source:
attachments:
links:
