datetime: '2026-02-14T17:05:29.726084+08:00'
source: (源链接)[book_structure_of_scientific_revolutions_files/book.html]
title: 深度精读：科学革命的结构 (第4版)
tags:
- philosophy-of-science
- paradigm-shift
- epistemology
