datetime: '2025-10-27T20:49:53.124767+08:00'
source: (源链接)[https://tim.blog/2007/12/05/how-to-take-notes-like-an-alpha-geek-plus-my-2600-date-challenge/]
title: 文章摘要：如何像专家一样做笔记 - Tim Ferriss
tags:
- productivity
- notes
- learning
