title: 批判性思维与生成式人工智能
datetime: '2025-10-13T14:50:48+08:00'
tags:
- critical-thinking
- ai
- education
description: 探讨批判性思维如何从狭隘的质疑工具演变为建设性对话,以及生成式AI如何从恐慌叙事中解放出来成为增强人类能力的工具,强调技术与道德良知结合的重要性。
source:
attachments:
links:
