title: Chrome DevTools (MCP) 为你的AI代理赋能
datetime: '2025-09-24T07:32:15+08:00'
tags:
- chrome-devtools
- mcp
- ai-development
description: Chrome DevTools MCP服务器公开预览版发布，将Chrome调试功能与AI编程助手连接，帮助AI代理实时调试网页、分析性能和修复问题。
source: (原文链接)[https://developer.chrome.com/blog/chrome-devtools-mcp]
attachments:
links:
- (MCP文档)[https://modelcontextprotocol.io/]
- (GitHub仓库)[https://github.com/google/chrome-devtools-mcp]