datetime: '2026-02-10T14:53:23.416304+08:00'
source: (源链接)[https://www.bilibili.com/video/BV1puFmzQEaK/]
title: AWS CEO Matt Garman 访谈深度复盘：构建 AI 时代的数字脊梁
tags:
- cloud-computing
- ai-infrastructure
- enterprise
