title: Anthropic Interviewer：1250 名职场人告诉我们的 AI 使用真相
datetime: '2025-12-16T12:43:01+08:00'
tags:
- ai
- research
- workplace
description: Anthropic 用 AI 驱动的访谈工具对 1250 名职场人、创意工作者和科学家进行访谈，了解他们对 AI 的真实看法和使用体验
source: (Anthropic Research)[https://anthropic.com/research/anthropic-interviewer]
attachments:
links:
