title: 软件工作中正在消失的"中间层"
datetime: '2026-01-06T17:56:55+08:00'
tags:
- ai
- coding-agent
- software-development
description: Linear CEO Karri Saarinen 探讨 AI coding agent 时代软件开发工作的重心变化，软件工作的中间层正在变薄，意图形成和结果验证变得更加重要。
source: (Karri Saarinen Twitter)[https://twitter.com/karrisaarinen]
attachments:
links:
