datetime: '2025-10-28T13:37:04.928594+08:00'
source: (源链接)[book_liberation_structures_power_files/book.html]
title: 📚 《释放性结构的惊人力量》核心摘要
tags:
 - structure
 - complexity
 - conversation
attachments:
 - (中文epub)[book.epub]