title: 半自动 AI 协作研究与学习的实践方法
datetime: '2025-10-14T16:37:49+08:00'
tags:
- ai
- research
- automation
description: 分享如何搭建半自动 AI 协作流程，通过选择顶级模型、自动化脚本处理和人工判断相结合，保持对信息源和上下文的控制权，实现高质量的研究与学习输出。
source: (原文)[write/20251014_ai_collaboration_workflow.md]
attachments:
links:
