title: 半自动 AI 协作研究与学习的实践方法
datetime: '2025-10-14T16:59:25+08:00'
tags:
- ai-workflow
- knowledge-management
- automation
description: 分享如何通过工具选择、自动化脚本和人工判断相结合，在 AI 时代保持对信息源和摘要上下文的控制权，实现高质量的研究与学习协作流程。
source: (原文)[/write/20251014_ai_collaboration_workflow.md]
attachments:
links:
