datetime: '2025-10-21T10:41:08.208118+08:00'
source: (源链接)[https://www.bilibili.com/video/BV1q5WUz6EEM/]
title: 对话 Sholto Douglas (Anthropic)：Claude 4.5 Sonnet 核心摘要
tags:
- anthropic
- interview
- technology
