title: AI 团队成员时代：管理复杂与不确定性软件项目的方法论演进
datetime: '2025-12-20T10:17:46+08:00'
tags:
- ai-development
- software-architecture
- agile
description: 探讨 AI 编码助手时代如何演进开发方法论，通过分层架构、知识管理、人在回路监督、PDCA 循环和混合 Agile-Waterfall 方法，在保持质量的同时充分利用 AI 加速软件开发。
source: (原创文章)[/write/20251219_managing_complex_projects_with_ai.md]
attachments:
links:
