title: XGo 社区观察：AI Coding 实践中的两种路径
datetime: '2025-10-13T17:40:10+08:00'
tags:
- ai-coding
- xgo
- development
description: XGo 用户群中许士伟和马工围绕 AI Coding 展开的实践讨论，展现了工匠路线与变革路线两种不同的应用思路，从工作流程、设计能力到组织变革的深度探讨。
source: (原文)[/write/20251013_ai_coding_debate_xgo_community.md]
attachments:
links:
