datetime: '2026-01-28T19:20:15.683931+08:00'
source: (源链接)[https://www.youtube.com/watch?v=kApsR0l9Jfw]
title: 'Steve Yegge: Agentic Coding 深度解析 & Beads 框架实战'
tags:
- ai-coding
- software-engineering
- workflow
