datetime: '2026-02-07T17:59:25.616148+08:00'
source: (源链接)[https://www.anthropic.com/engineering/building-c-compiler]
title: 传统 SDE 视角：工程拆解与 Spec 管理技巧
tags:
- software-engineering
- ai-coding
- specification
