title: AI 不是软件
datetime: '2025-09-19T11:45:38+08:00'
tags:
- artificial-intelligence
- software-engineering
- philosophy
description: 探讨为什么 AI 系统不应该被视为传统软件，分析两者在创建方式、运行机制和故障处理方面的根本差异，提出需要新的思维模式来理解 AI 的本质。
source: (LessWrong 原文)[https://www.lesswrong.com/posts/iknSNTbb8deJwQuLJ/ai-is-not-software]
attachments:
links:
- (相关讨论：深度学习的本质)[https://www.lesswrong.com/]