title: 离经叛道的衰落：那些怪诞的事物都去哪儿了？
datetime: '2026-01-20T10:24:30+08:00'
tags:
- deviance
- culture
- society
description: 通过大量数据分析展示现代社会中离经叛道行为的衰落趋势，从青少年行为到文化创新，从科学进步到建筑设计，各个领域都呈现出同质化和停滞的现象。文章探讨了这一趋势背后的原因以及对未来的影响。
source: (The Decline of Deviance - Experimental History)[https://www.experimental-history.com/p/the-decline-of-deviance]
attachments:
links:
- (Experimental History)[https://www.experimental-history.com]
