title: 离经叛道的衰落 - 那些怪诞的事物都去哪儿了？
datetime: '2026-01-20T02:35:44+08:00'
tags:
- deviance
- culture
- society
description: 现在的人不如以前那么"怪"了。来自社会各个领域的数据都强有力地指向同一个方向：我们正处于一场恶作剧的衰退期、一场循规蹈矩的危机，以及一场平庸的流行病之中。离经叛道正在衰落。本文通过大量数据分析了这一现象，探讨了从青少年行为、犯罪率、文化创新到科学进步等多个维度的变化趋势。
source: (Experimental History - The Decline of Deviance)[https://www.experimental-history.com]
attachments:
links:
- (原文链接)[https://www.experimental-history.com]
