datetime: '2025-12-24T22:06:18.881442+08:00'
source: (源链接)[book_psychology_philosophy_of_stress_files/book.html]
title: 深度摘要：《压力、文化与社区》 - Stevan E. Hobfoll
tags:
- psychology
- stress-management
- community
