datetime: '2025-12-08T09:39:41.433098+08:00'
source: (翻译版)[report_openrouter_state_of_ai_files/book.html]
title: 2025 AI 现状深度报告：100万亿 Token 实证分析

links: 
 - (源链接)[https://openrouter.ai/state-of-ai]

attachments:
 - (中文PDF)[book.pdf]

tags:
 - ai-coding
 - openrouter
 - report