title: GitHub Octoverse 2025：每秒一位新开发者加入，AI 助推 TypeScript 登顶
datetime: '2025-12-24T12:24:57+08:00'
tags:
- github
- ai
- typescript
description: GitHub 2025 年度 Octoverse 报告完整翻译，揭示 AI、Agent 和强类型语言如何驱动软件开发领域十多年来最大的变革，TypeScript 首次超越 Python 成为最流行语言。
source: (GitHub Octoverse 2025)[https://github.blog/news-insights/octoverse/octoverse-2025/]
attachments:
links:
- (GitHub Blog)[https://github.blog/]
