title: GitHub Octoverse 2025：每秒一位新开发者加入，AI 助推 TypeScript 登顶
datetime: '2025-12-24T12:54:22+08:00'
tags:
- github
- ai
- typescript
description: GitHub 2025年度Octoverse报告揭示AI、Agent和强类型语言如何驱动软件开发领域最大变革，TypeScript首次登顶，每秒一位新开发者加入GitHub
source: (GitHub Octoverse 2025 Report)[https://github.blog/news-insights/octoverse/octoverse-2025/]
attachments:
links:
- (GitHub Blog)[https://github.blog/]
