title: 你是读还是听，决定了你是用直觉还是理性在思考
datetime: '2025-12-23T11:21:02+08:00'
tags:
- cognition
- psychology
- thinking
description: 研究发现阅读与聆听会激活不同的思维模式：听信息更依赖直觉，读信息更倾向分析性思考。这与语言习得方式有关，对日常决策和公共政策都有启示。
source: (Do you think more clearly when reading or when listening?)[https://psyche.co/ideas/do-you-think-more-clearly-when-reading-or-when-listening]
attachments:
links:
