datetime: '2025-09-21T09:40:04.599854+08:00'
source: (源链接)[https://github.com/huggingface/evaluation-guidebook/blob/main/yearly_dives/2025-evaluations-for-useful-models.md]
title: 'Evals in 2025: 核心要点摘要'
