datetime: '2026-02-22T17:47:35.347921+08:00'
source: (源链接)[https://www.bilibili.com/video/BV1qbfwB7Ezw/]
title: Claude Code Agent Teams：从协作涌现到认知重构
tags:
- claude-code
- multi-agent
- team-collaboration
