datetime: '2025-11-03T16:58:31.352951+08:00'
source: (源链接)[https://www.xiaoyuzhoufm.com/episode/68f7034122654730207b940c?s=eyJ1IjogIjY0YzcxMDJkZWRjZTY3MTA0YTNhNWFjNyJ9]
title: 乱翻书:中视频战争复盘
tags:
- platform-competition
- product-strategy
- content-creator
