datetime: '2025-10-15T21:59:23.911359+08:00'
source: (源链接)[https://www.bilibili.com/video/BV1Fi4Bz4EaD/]
title: 'Andrew Ng 访谈摘要: AI编码的革命与创业新范式'
tags:
- artificial-intelligence
- entrepreneurship
- coding
