title: LLM 在空白输入时的幻觉问题
datetime: '2025-10-24T12:03:41+08:00'
tags:
- llm
- hallucination
- ai
description: 探讨 LLM 在处理空白或信息量不足的输入时产生幻觉的现象,包括代码审查、文档生成、语音识别和图像 OCR 等场景的实际案例与应对方法。
source: (原创文章)[/write/20251024_llm_hallucination_on_blank_input.md]
attachments:
links:
