title: 2025年中期大语言模型市场更新：基础模型格局与经济学
datetime: '2025-09-24T12:37:46+08:00'
tags:
- llm
- market
- anthropic
description: Anthropic成为新的企业AI领导者，模型API支出激增至84亿美元，代码生成成为AI首个突破性用例的市场分析报告。
source: (2025 Mid-Year LLM Market Update)[https://menlovc.com/perspective/2025-mid-year-llm-market-update/]
attachments:
links:
- (Menlo Ventures AI报告)[https://menlovc.com/2024-the-state-of-generative-ai-in-the-enterprise/]