title: Jeff Bezos 的高效会议三原则
datetime: '2025-11-19T19:23:12+08:00'
tags:
- meeting
- productivity
- management
description: Amazon CEO Jeff Bezos 通过三条简单规则破解高效会议密码：两个披萨团队规则控制人数、用叙事备忘录替代 PowerPoint、会议开始时集体默读文档。这些方法确保团队保持敏捷、思考清晰并充分准备。
source: (Inc.com - Jeff Bezos Knows How to Run a Meeting)[https://www.inc.com/justin-bariso/jeff-bezos-knows-how-to-run-a-meeting-heres-how-he-does-it.html]
attachments:
links:
